#!/bin/bash

# Clear Tokens Script
# Fixes "Invalid refresh token" errors by clearing browser storage

echo "🔧 Token Cleanup Script"
echo "======================="
echo ""
echo "This script will help you clear invalid tokens from your browser."
echo ""
echo "⚠️  IMPORTANT: You need to manually clear browser data"
echo ""
echo "📋 Steps to fix 'Invalid refresh token' error:"
echo ""
echo "1. Open your browser (Chrome/Safari/Firefox)"
echo "2. Open Developer Tools (F12 or Cmd+Option+I on Mac)"
echo "3. Go to the 'Application' tab (Chrome) or 'Storage' tab (Firefox)"
echo "4. In the left sidebar, find 'Local Storage'"
echo "5. Click on 'http://localhost:5173'"
echo "6. Right-click and select 'Clear' or delete these keys:"
echo "   - accessToken"
echo "   - refreshToken"
echo "   - user"
echo ""
echo "OR use this quick method:"
echo ""
echo "Chrome/Edge:"
echo "  1. Press Cmd+Shift+Delete (Mac) or Ctrl+Shift+Delete (Windows)"
echo "  2. Select 'Cookies and other site data'"
echo "  3. Select 'All time'"
echo "  4. Click 'Clear data'"
echo ""
echo "Safari:"
echo "  1. Go to Safari > Preferences > Privacy"
echo "  2. Click 'Manage Website Data'"
echo "  3. Search for 'localhost'"
echo "  4. Click 'Remove' then 'Done'"
echo ""
echo "Firefox:"
echo "  1. Press Cmd+Shift+Delete (Mac) or Ctrl+Shift+Delete (Windows)"
echo "  2. Select 'Cookies'"
echo "  3. Select 'Everything'"
echo "  4. Click 'Clear Now'"
echo ""
echo "✅ After clearing:"
echo "  1. Close all browser tabs with localhost:5173"
echo "  2. Restart your browser (optional but recommended)"
echo "  3. Go to http://localhost:5173"
echo "  4. Login again with: admin@example.com / admin123"
echo ""
echo "🔄 Alternative: Use Incognito/Private browsing mode"
echo "   This automatically starts with clean storage"
echo ""

read -p "Press Enter after you've cleared the browser data..."

echo ""
echo "✅ Great! Now try accessing the application again."
echo "   If you still see errors, run: ./restart-servers.sh"
echo ""

# Made with Bob
