#!/bin/bash

echo "🧹 Clear Browser Data Instructions"
echo "=================================="
echo ""
echo "You have old refresh tokens in your browser cookies."
echo "Please follow these steps:"
echo ""
echo "Option 1: Clear Cookies (Recommended)"
echo "  1. Open your browser"
echo "  2. Press F12 to open Developer Tools"
echo "  3. Go to 'Application' tab (Chrome) or 'Storage' tab (Firefox)"
echo "  4. Click 'Cookies' in the left sidebar"
echo "  5. Click 'http://localhost:5173'"
echo "  6. Delete the 'refreshToken' cookie"
echo "  7. Refresh the page"
echo ""
echo "Option 2: Use Incognito/Private Window"
echo "  1. Open a new Incognito/Private window"
echo "  2. Go to http://localhost:5173/admin/login"
echo "  3. Login with admin@example.com / admin123"
echo ""
echo "Option 3: Clear All Site Data"
echo "  Chrome: Settings → Privacy → Clear browsing data → Cookies"
echo "  Firefox: Settings → Privacy → Clear Data → Cookies"
echo "  Safari: Preferences → Privacy → Manage Website Data → Remove All"
echo ""
echo "After clearing cookies, login again with:"
echo "  Email: admin@example.com"
echo "  Password: admin123"
echo ""
